[project]
name = "sample"
version = "0.1.0"
description = "Sample simulator for the app template"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.13",
    "pydoover>=0.4.10",
]

[project.scripts]
doover-app-run = "main:main"
